Repository yalla-coop/universal-credit-support, pull requests merged in 2021-08, with the labels that each got.

#89 59 add new icons
  client/src/components/CallUsLink/CallUsLink.stories.js
  client/src/components/CallUsLink/index.js
  client/src/components/CallUsLink/style.js
  client/src/components/Icon/icons/Add.js
  client/src/components/Icon/icons/Checklist1.js
  client/src/components/Icon/icons/Checklist2.js
  client/src/components/Icon/icons/Flag.js
  client/src/components/Icon/icons/ForwardArrow.js
  client/src/components/Icon/icons/Menu.js
  client/src/components/Icon/icons/Open.js
  client/src/components/Icon/icons/Time.js
  client/src/components/Icon/index.js
  client/src/components/Layout/General/index.js
  client/src/components/TextWithIcon/TextWithIcon.stories.js
  client/src/components/TextWithIcon/index.js
  client/src/components/TextWithIcon/style.js
  client/src/components/assets/DesktopLogo.svg
  client/src/components/assets/MobileLogo.svg
  client/src/components/index.js
  client/src/pages/Step/index.js
Labels: awaiting-review

#88 Update theme
  client/src/components/Button/style.js
  client/src/components/Cards/index.js
  client/src/components/Inputs/Dropdown/style.js
  client/src/components/Layout/General/style.js
  client/src/components/Typography/index.js
  client/src/pages/Home/index.js
  client/src/pages/Step/style.js
  client/src/theme/colors.js
  client/src/theme/global-style.js
  client/src/theme/gradients.js
  client/src/theme/index.js
Labels: awaiting-review

#90 61 update buttons
  client/src/components/Button/Button.stories.js
  client/src/components/Button/index.js
  client/src/components/Button/style.js
  client/src/components/HelpButton/HelpButton.stories.js
  client/src/components/HelpButton/index.js
  client/src/components/HelpButton/style.js
  client/src/stories/colors.stories.js
  client/src/theme/colors.js
Labels: awaiting-review

#92 69 help
  client/src/components/HelpButton/HelpButton.stories.js
  client/src/components/HelpButton/index.js
  client/src/components/HelpButton/style.js
  client/src/theme/borders.js
Labels: awaiting-review

#95 60 add layouts and 63 add menu
  client/src/App.js
  client/src/components/Icon/icons/Menu.js
  client/src/components/Layout/Dashboard/index.js
  client/src/components/Layout/Dashboard/style.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/General/style.js
  client/src/components/Layout/SplitScreen/index.js
  client/src/components/Layout/SplitScreen/style.js
  client/src/components/Layout/index.js
  client/src/components/Modal/index.js
  client/src/components/Modal/style.js
  client/src/components/Navbar/NavRoutes.js
  client/src/components/Navbar/Navbar.stories.js
  client/src/components/Navbar/index.js
  client/src/components/Navbar/style.js
  client/src/components/Route/index.js
  client/src/components/assets/EN.png
  client/src/components/assets/YallaLogo.png
  client/src/constants/nav-routes.js
  client/src/constants/roles.js
  client/src/constants/translations/english/index.js
  client/src/constants/translations/english/menu-items.js
  client/src/pages/Step/index.js
  client/src/theme/global-style.js
Labels: requested-changes

#94 56 setup database
  .gitignore
  server/config/index.js
  server/constants/data-type.js
  server/database/build-tables.js
  server/database/build.js
  server/database/build.script.js
  server/database/connect.js
  server/database/dummy-data-prod/build.js
  server/database/dummy-data-prod/build.script.js
  server/database/dummy-data-prod/index.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data-prod/users.js
  server/database/dummy-data/dummy-data.js
  server/database/dummy-data/index.js
  server/database/dummy-data/organisations.js
  server/database/dummy-data/users.js
  server/database/index.js
  server/database/init/auto-timestamps.sql
  server/database/init/index.js
  server/database/init/migrations.sql
  server/database/init/types.sql
  server/database/models/content-audit-log/index.js
  server/database/models/content-audit-log/schema.sql
  server/database/models/index.js
  server/database/models/landing-page-content/index.js
  server/database/models/landing-page-content/schema.sql
  server/database/models/media/index.js
  server/database/models/media/schema.sql
  server/database/models/organisations/index.js
  server/database/models/organisations/schema.sql
  server/database/models/steps/index.js
  server/database/models/steps/schema.sql
  server/database/models/users/index.js
  server/database/models/users/schema.sql
  server/database/utils/index.js
  server/database/utils/sanitize-csv-injection.js
  server/database/utils/to-camelcase.js
  server/database/utils/to-parent-child.js
  server/database/utils/utils.spec.js
Labels: awaiting-review

#100 Add all step content > #57
  server/constants/data-type.js
  server/database/dummy-data-prod/index.js
  server/database/dummy-data-prod/landing-page-content.js
  server/database/dummy-data-prod/steps-content.js
  server/database/dummy-data/index.js
  server/database/models/steps/schema.sql
Labels: requested-changes

#99 67 landing (FRONT)
  client/src/App.js
  client/src/components/HelpButton/style.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/General/style.js
  client/src/components/Steps/index.js
  client/src/components/Steps/style.js
  client/src/components/TextWithIcon/index.js
  client/src/components/TextWithIcon/style.js
  client/src/components/assets/BackgroundHydeLogo.svg
  client/src/context/steps.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.js
  client/src/theme/index.js
  server/database/dummy-data-prod/prod-data.js
Labels: approved

#97 96 remove modal
  client/public/index.html
  client/src/App.js
  client/src/components/Layout/Step/index.js
  client/src/components/Layout/Step/style.js
  client/src/components/Layout/index.js
  client/src/components/Modal/index.js
  client/src/components/Modal/style.js
  client/src/components/index.js
  client/src/pages/Step/index.js
  client/src/pages/Step/style.js
  client/src/theme/index.js
Labels: awaiting-review

#103 71 create login logout pages
  client/src/App.js
  client/src/components/Button/Button.stories.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Login/index.js
  client/src/pages/Login/style.js
  client/src/pages/index.js
Labels: awaiting-review

#102 74 create unique link
  client/src/App.js
  client/src/api-calls/organisations.js
  client/src/components/Route/index.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/context/auth.js
  client/src/helpers/authorization.js
  client/src/helpers/index.js
  client/src/pages/CreateUniqueLink/Success.js
  client/src/pages/CreateUniqueLink/index.js
  client/src/pages/CreateUniqueLink/style.js
  client/src/pages/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/create-unique-link.js
  client/src/validation/schemas/index.js
  server/api/index.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data/organisations.js
  server/database/models/organisations/schema.sql
  server/modules/organisation/controllers/get-organisation.js
  server/modules/organisation/controllers/index.js
  server/modules/organisation/controllers/update-organisation.js
  server/modules/organisation/model/find.js
  server/modules/organisation/model/update.js
  server/modules/organisation/use-cases/get-organisation.js
  server/modules/organisation/use-cases/update-organisation.js
  server/services/error-handler/messages.js
Labels: approved

#101 65 fetch step content backend
  client/package-lock.json
  client/src/api-calls/landing-page.js
  client/src/api-calls/steps.js
  client/src/components/Steps/index.js
  client/src/constants/translations/english/error-msgs.js
  client/src/context/steps.js
  client/src/pages/Home/LandingContent.js
  client/src/pages/Home/index.js
  server/api/index.js
  server/modules/landing-page/controllers/get-landing-page.js
  server/modules/landing-page/model/find.js
  server/modules/landing-page/use-cases/get-landing-page.js
  server/modules/step/controllers/get-steps.js
  server/modules/step/model/find.js
  server/modules/step/use-cases/get-steps.js
Labels: awaiting-review

#104 75 create dashboad page
  client/src/App.js
  client/src/api-calls/landing-page.js
  client/src/api-calls/steps.js
  client/src/components/Layout/Dashboard/index.js
  client/src/components/Navbar/index.js
  client/src/components/Typography/index.js
  client/src/components/index.js
  client/src/constants/nav-routes.js
  client/src/context/steps.js
  client/src/pages/Dashboard/index.js
  client/src/pages/Dashboard/style.js
  client/src/pages/index.js
Labels: awaiting-review

#108 Create admin into pages
  .vscode/settings.json
  client/src/App.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Login/index.js
  client/src/pages/Welcome/Welcome1.js
  client/src/pages/Welcome/Welcome2.js
  client/src/pages/Welcome/index.js
  client/src/pages/index.js
Labels: awaiting-review

#105 68 Update step page (FRONT)
  client/src/components/Cards/Checklist/index.js
  client/src/components/Cards/Checklist/style.js
  client/src/components/Cards/Tips/index.js
  client/src/components/Cards/Tips/style.js
  client/src/components/HelpButton/index.js
  client/src/components/HelpButton/style.js
  client/src/components/Icon/icons/Compass.js
  client/src/components/Icon/index.js
  client/src/components/Layout/Step/style.js
  client/src/components/Steps/style.js
  client/src/components/TextWithIcon/index.js
  client/src/components/TextWithIcon/style.js
  client/src/components/Typography/index.js
  client/src/components/index.js
  client/src/constants/data-types.js
  client/src/constants/index.js
  client/src/context/steps.js
  client/src/pages/Home/style.js
  client/src/pages/Step/index.js
  client/src/pages/Step/style.js
  client/src/theme/index.js
  server/database/dummy-data-prod/steps-content.js
  server/database/models/steps/schema.sql
  server/modules/step/model/find.js
  server/modules/step/use-cases/get-steps.js
Labels: approved

#117 Create modal
  client/src/components/Modal/Modal.stories.js
  client/src/components/Modal/index.js
  client/src/components/Modal/style.js
Labels: awaiting-review

#118 build: forget password user flow (FE)
  client/package-lock.json
  client/src/App.js
  client/src/constants/nav-routes.js
  client/src/pages/ForgotPassword/index.js
  client/src/pages/ForgotPassword/style.js
  client/src/pages/ResetPassword/index.js
  client/src/pages/ResetPassword/style.js
  client/src/pages/index.js
  client/src/validation/schemas/forgot-password.js
  client/src/validation/schemas/reset-password.js
Labels: awaiting-review

#106 72 signup login
  client/src/App.js
  client/src/components/Icon/index.js
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Inputs/Checkbox/style.js
  client/src/constants/data-types.js
  client/src/constants/nav-routes.js
  client/src/constants/translations/english/menu-items.js
  client/src/context/auth.js
  client/src/pages/Login/index.js
  client/src/pages/Login/style.js
  client/src/pages/Signup/index.js
  client/src/pages/Signup/style.js
  client/src/pages/index.js
  client/src/theme/colors.js
  client/src/validation/schemas/signup.js
  package.json
  server/api/middlewares/authenticate.js
  server/constants/data-type.js
  server/database/dummy-data/index.js
  server/database/dummy-data/organisations.js
  server/database/dummy-data/users.js
  server/database/init/types.sql
  server/database/models/organisations/schema.sql
  server/database/models/users/schema.sql
  server/helpers/create-org-slug.js
  server/helpers/index.js
  server/modules/organisation/model/create.js
  server/modules/organisation/model/find.js
  server/modules/user/controllers/login.js
  server/modules/user/controllers/signup.js
  server/modules/user/model/create.js
  server/modules/user/model/find.js
  server/modules/user/use-cases/login.js
  server/modules/user/use-cases/signup.js
  server/modules/user/utils/validate-signup.js
  server/services/validation/fields.js
Labels: awaiting-review

#110 52 setup sentry
  client/package-lock.json
  client/package.json
  client/src/ErrorBoundary.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/config/common.js
  server/services/error-handler/configure-sentry.js
  server/services/error-handler/index.js
Labels: awaiting-review

#127 build: edit details page (FE)
  client/src/App.js
  client/src/constants/translations/english/index.js
  client/src/pages/EditDetails/index.js
  client/src/pages/EditDetails/style.js
  client/src/pages/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/edit-details.js
  client/src/validation/schemas/index.js
  package-lock.json
Labels: awaiting-review

#132 124 fix create unique link bug
  client/src/App.js
  client/src/components/Route/index.js
  client/src/constants/nav-routes.js
  client/src/constants/roles.js
  client/src/pages/CreateOrganisationDetails/SecondStep.js
  client/src/pages/CreateOrganisationDetails/index.js
  client/src/pages/CreateUniqueLink/Success.js
  client/src/pages/CreateUniqueLink/index.js
  client/src/pages/EditDetails/index.js
  client/src/pages/Login/index.js
  client/src/pages/Signup/index.js
  server/database/dummy-data/organisations.js
  server/modules/landing-page/controllers/index.js
  server/modules/media/controllers/get-signed-url.js
  server/modules/media/controllers/index.js
  server/modules/organisation/controllers/get-organisation.js
  server/modules/organisation/controllers/index.js
  server/modules/organisation/controllers/update-organisation.js
  server/modules/organisation/model/find.js
  server/modules/organisation/use-cases/get-organisation.js
  server/modules/organisation/use-cases/update-organisation.js
  server/modules/user/controllers/signup.js
Labels: awaiting-review

#136 connect front with back for edit page
  client/src/api-calls/organisations.js
  client/src/pages/CreateUniqueLink/index.js
  client/src/pages/EditDetails/index.js
  client/src/pages/StepForm/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/edit-details.js
  server/modules/organisation/controllers/get-organisation.js
  server/modules/organisation/controllers/update-organisation.js
  server/modules/organisation/model/find.js
  server/modules/organisation/model/update.js
  server/modules/organisation/use-cases/get-organisation.js
  server/modules/organisation/use-cases/update-organisation.js
  server/modules/user/model/update.js
Labels: awaiting-review

#138 134 create changes page
  client/src/App.js
  client/src/api-calls/content-audi-logs.js
  client/src/pages/Changes/index.js
  client/src/pages/Changes/style.js
  client/src/pages/index.js
  server/modules/content-audit-log/controllers/get-audit-log.js
  server/modules/content-audit-log/controllers/get-audit-logs.js
  server/modules/content-audit-log/controllers/index.js
  server/modules/content-audit-log/model/find.js
  server/modules/content-audit-log/use-cases/get-audit-log.js
  server/modules/content-audit-log/use-cases/get-audit-logs.js
  server/modules/content-audit-log/use-cases/index.js
  server/modules/landing-page/controllers/update-landing-page.js
  server/modules/landing-page/model/update.js
  server/modules/landing-page/use-cases/update-landing-page.js
  server/modules/step/controllers/update-step.js
  server/modules/step/model/update.js
  server/modules/step/use-cases/update-step.js
Labels: awaiting-review

#139 build: customise page
  client/src/App.js
  client/src/components/Inputs/ImageUpload/style.js
  client/src/pages/Customise/index.js
  client/src/pages/Customise/style.js
  client/src/pages/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/customise.js
  client/src/validation/schemas/index.js
  server/modules/organisation/model/find.js
Labels: awaiting-review

#125 86 create org page
  client/src/App.js
  client/src/api-calls/users.js
  client/src/components/Modal/index.js
  client/src/components/index.js
  client/src/pages/Organisations/index.js
  client/src/pages/Organisations/style.js
  client/src/pages/index.js
  server/modules/user/controllers/delete-user.js
  server/modules/user/controllers/get-users.js
  server/modules/user/controllers/index.js
  server/modules/user/controllers/update-user.js
  server/modules/user/model/find.js
  server/modules/user/model/remove.js
  server/modules/user/model/update.js
  server/modules/user/use-cases/delete-user.js
  server/modules/user/use-cases/get-users.js
  server/modules/user/use-cases/index.js
  server/modules/user/use-cases/update-user-role.js
Labels: awaiting-review

#135 126 fix menu bugs
  client/src/components/Navbar/NavRoutes.js
  client/src/constants/nav-routes.js
  client/src/constants/translations/english/menu-items.js
  client/src/context/auth.js
  client/src/pages/Dashboard/index.js
Labels: awaiting-review

#143 134 create changes page
  client/src/App.js
  client/src/api-calls/content-audi-logs.js
  client/src/constants/nav-routes.js
  client/src/pages/Changes/index.js
  client/src/pages/Changes/style.js
  client/src/pages/index.js
  server/modules/content-audit-log/controllers/get-audit-log.js
  server/modules/content-audit-log/controllers/get-audit-logs.js
  server/modules/content-audit-log/controllers/index.js
  server/modules/content-audit-log/model/find.js
  server/modules/content-audit-log/use-cases/get-audit-log.js
  server/modules/content-audit-log/use-cases/get-audit-logs.js
  server/modules/content-audit-log/use-cases/index.js
  server/modules/landing-page/controllers/update-landing-page.js
  server/modules/landing-page/model/update.js
  server/modules/landing-page/use-cases/update-landing-page.js
  server/modules/step/controllers/update-step.js
  server/modules/step/model/update.js
  server/modules/step/use-cases/update-step.js
Labels: awaiting-review

#146 fix: steps coloring based on step state
  client/src/components/Steps/index.js
  client/src/components/Steps/style.js
  client/src/pages/Home/index.js
  server/database/build-tables.js
  server/database/dummy-data-prod/steps-content.js
Labels: awaiting-review

#120 fix steps alignment
  client/src/components/Steps/index.js
  client/src/components/Steps/style.js
  client/src/pages/Home/index.js
Labels: awaiting-review

#147 handle delete users
  client/src/pages/Admin/index.js
  client/src/pages/Home/style.js
  server/database/models/users/schema.sql
  server/modules/user/model/find.js
  server/modules/user/model/remove.js
  server/modules/user/model/update.js
  server/modules/user/use-cases/delete-user.js
Labels: awaiting-review

#148 show logo for claimants
  client/src/App.js
  client/src/api-calls/organisations.js
  client/src/components/HelpButton/index.js
  client/src/components/Inputs/ImageUpload/index.js
  client/src/components/Layout/Dashboard/index.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/SplitScreen/index.js
  client/src/components/Navbar/index.js
  client/src/components/OrganisationLogo/index.js
  client/src/components/assets/BackgroundHydeLogo.svg
  client/src/components/assets/DesktopLogo.svg
  client/src/components/assets/MobileLogo.svg
  client/src/components/assets/YallaLogo.png
  client/src/components/index.js
  client/src/context/admin-org.js
  client/src/context/public-org.js
  client/src/pages/Admin/CreateOrganisationDetails/SecondStep.js
  client/src/pages/Admin/CreateUniqueLink/Success.js
  client/src/pages/Admin/CreateUniqueLink/index.js
  client/src/pages/Admin/Dashboard/index.js
  client/src/pages/Admin/EditDetails/index.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.js
  client/src/pages/Step/index.js
  client/src/pages/Step/style.js
  server/modules/organisation/controllers/get-benefit-calculator.js
  server/modules/organisation/controllers/get-help-details.js
  server/modules/organisation/controllers/get-organisation-by-unique-slug.js
  server/modules/organisation/controllers/index.js
  server/modules/organisation/model/find.js
  server/modules/organisation/use-cases/get-benefit-calculator.js
  server/modules/organisation/use-cases/get-help-details.js
  server/modules/organisation/use-cases/get-organisation-by-unique-slug.js
  server/modules/organisation/use-cases/index.js
Labels: awaiting-review

#149 fix production data
  package-lock.json
  package.json
  server/config/server.js
  server/database/dummy-data-prod/index.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data-prod/prod-data.js
  server/database/dummy-data-prod/users.js
Labels: awaiting-review

#151 disable csp
  server/api/middlewares/helmet.js
Labels: awaiting-review
